name: Check Home Assistant Configuration

on:
  push:
  pull_request:

jobs:
  check-config:
    runs-on: ubuntu-latest
    name: Check Home Assistant Configuration
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Home Assistant configuration
        uses: docker://homeassistant/home-assistant:stable
        with:
          args: hass -c /github/workspace --script check_config